spring.jpa.show-sql=false

spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never

logging.level.com.spectrumai=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.security=WARN
